CTK_VERSION=ctk-0.1

# CTK LIB Path
CTK_PATH=$$PWD/CTK-Src

#DIR_DEPEND_CTK_DEST=$${CTK_PATH}/Lib/$${DIR_PLATFORM}/$${DIR_COMPILEMODE}/$${CTK_VERSION}
DIR_DEPEND_CTK_DEST=$$PWD/Bin/$${DIR_PLATFORM}/$${DIR_COMPILEMODE}

INCLUDEPATH +=$${CTK_PATH}/Include/$${CTK_VERSION}/
